### ISSUE TITLE
module 'comfy.sd' has no attribute 'load_diffusion_model_state_dict'

### ISSUE THREAD

**Issue by IntellectzProductions** [city96/ComfyUI-GGUF#101]
Error occurred when executing UnetLoaderGGUF:

module 'comfy.sd' has no attribute 'load_diffusion_model_state_dict'

File "J:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "J:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "J:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "J:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF\nodes.py", line 259, in load_unet
model = comfy.sd.load_diffusion_model_state_dict(

I do not understand why this error is happening. I can't update comfy any more than it is. If somebody can help with what is going on with this error.

**Comment by city96** [comment]
The `ComfyUI_windows_portable\update` folder should have a filed called `update_comfyui.bat` - Does this one complete the update successfully or does it throw an error?

**Comment by al-swaiti** [comment]
i made this manual setup for comfyui in windows try it 
https://civitai.com/articles/7088/manual-comfyui-setupwin

**Comment by city96** [comment]
@al-swaiti This has nothing to do with updating an existing install. Please stop advertising your own guides and models in this repository.

**Comment by al-swaiti** [comment]
do you think doing this an ads , when u did gguf it was ads for you !

**Comment by al-swaiti** [comment]
keep in your mind ,,,, all things it was to support u ! good luck

**Comment by city96** [comment]
@al-swaiti This issue is about the standalone install from the official repository, and your post doesn't mention anything about updating either the standalone or the manual version. Asking someone to reinstall just to update is unreasonable. A guide on how to update the standalone or troubleshoot issues would make more sense to link, but this just looks like you're advertising.

Your guide is mostly the [the official guide from the ComfyUI repo](https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#manual-install-windows-linux) + a step by step for how to install the manager. I don't think this is relevant to this repo/issue and there's already tons of different guides like it on the internet.

**Comment by al-swaiti** [comment]
i made that because they tell me there is not guid for windows search again ! 
its okay  ,,, you can delete my messages  ,,,
if i were u ill say thanks for your time ,,,
you said  to him to use update bat file which is from old repo ,,, !!!! 
he must download new one 
the best to pypass this issues is to git clone and then use update from manager ,,,

**Comment by city96** [comment]
Checked, that bat file is present on latest standalone. It creates a backup of the current version and updates to latest.

![image](https://github.com/user-attachments/assets/6535e92c-e442-404d-8528-91947c78fac9)

**Comment by al-swaiti** [comment]
when you go advanced in comfyui , the issues start increasing with  portable versions ,  So the best create env install libraries and run comfyui  ,,, its more comfortable and better with device  original drivers

**Comment by al-swaiti** [comment]
> @al-swaiti This has nothing to do with updating an existing install. Please stop advertising your own guides and models in this repository.

yesterday i saw some thing about zram or swap but i didnt share my stuff https://civitai.com/articles/6880/flux-saunaincrease-your-ram because i cant  try it on  my virtual windows machine

**Comment by 2364814106** [comment]
this error also happened in my comfyui, it has been solved? help me, my god

**Comment by 2364814106** [comment]
my error is this:

Error occurred when executing DualCLIPLoaderGGUF:

module 'comfy.sd' has no attribute 'load_text_encoder_state_dicts'

File "D:\fooocus\ComfyUI-aki-v1.3\execution.py", line 316, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "D:\fooocus\ComfyUI-aki-v1.3\execution.py", line 191, in get_output_data
return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
File "D:\fooocus\ComfyUI-aki-v1.3\execution.py", line 168, in _map_node_over_list
process_inputs(input_dict, i)
File "D:\fooocus\ComfyUI-aki-v1.3\execution.py", line 157, in process_inputs
results.append(getattr(obj, func)(**inputs))
File "D:\fooocus\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-GGUF\nodes.py", line 305, in load_clip
return (self.load_patcher(clip_paths, clip_type, self.load_data(clip_paths)),)
File "D:\fooocus\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-GGUF\nodes.py", line 264, in load_patcher
clip = comfy.sd.load_text_encoder_state_dicts(

**Comment by city96** [comment]
Well, on latest ComfyUI the "load_text_encoder_state_dicts" is present [right here](https://github.com/comfyanonymous/ComfyUI/blob/cf80d28689c1dfa8d22d7fa8e68db7ea3de0fd37/comfy/sd.py#L409) so all I can offer is the same advice as above about updating ComfyUI.

**Comment by 2364814106** [comment]
v~寂
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "city96/ComfyUI-GGUF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月14日(星期六) 凌晨1:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [city96/ComfyUI-GGUF] module 'comfy.sd' has no attribute 'load_diffusion_model_state_dict' (Issue #101)





 
Well, on latest ComfyUI the "load_text_encoder_state_dicts" is present right here so all I can offer is the same advice as above about updating ComfyUI.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.




thank you very much, after update the comfyui, the error is solved, you are really&nbsp;Awesome！！Message ID: ***@***.***&gt;

**Comment by city96** [comment]
I was going to add a warning that pops up and prompts the user to update but I forgot about it lol. But yeah, I'll close this.
