### ISSUE TITLE
Hi, City96, Interested in cost some time to study this model? 

### ISSUE THREAD

**Issue by wikeeyang** [city96/ComfyUI-GGUF#120]
https://huggingface.co/nyanko7/flux-dev-de-distill, This De distillation model works well, have more detail can be presented than the Dev model. it had adjusted the q/k/v parameters...

**Comment by city96** [comment]
A bit late since I've been out of the loop on stuff the past month or so but I've updated the convert script to properly work with it. https://github.com/city96/ComfyUI-GGUF/commit/d090a910ac17e4ce256f35e83bce581c4e5673f8

It would've worked without that change as well but the resulting gguf files would've been in a non-standard format that wouldn't have worked on forge/sd.cpp/etc.

**Comment by wikeeyang** [comment]
@city96 Thanks a lot! I will try the script to convert it and test then.

**Comment by city96** [comment]
Closing this. Also, there's some quants up on huggingface of that model now: https://huggingface.co/TheYuriLover/flux-dev-de-distill-GGUF
