### ISSUE TITLE
raise ValueError(f"Unknown model architecture!")

### ISSUE THREAD

**Issue by bananasss00** [city96/ComfyUI-GGUF#13]
![image](https://github.com/user-attachments/assets/636da62d-6757-42d6-87d1-1f87fdffa5c8)

I get this error on all models sd15, sdxl, flux.

It should be clarified that I have all models stored in fp8 format.

**Comment by city96** [comment]
This is on purpose for sd15 / sdxl. They don't benefit from quantization and shouldn't be quantized unless you need a test model for development work. It will only accept the UNET in diffusers format and that check is there in order to stop people from quantizing random models in invalid formats that include the VAE / text encoders.

**Comment by doggeddalle** [comment]
I just get this error in comfy even when UNET for Flux D

```
> e:\comfyui\custom_nodes\comfyui-gguf\tools\convert.py(80)detect_arch()
-> raise ValueError("Unknown model architecture!")
(Pdb)
```

Originally I was trying to run nf4 unet with q8.0 gguf flux clip but even with normal flux its just the above issue
