### ISSUE TITLE
No VAE output option in UnetLoaderGGUF

### ISSUE THREAD

**Issue by Amazon90** [city96/ComfyUI-GGUF#139]
There is no VAE output option in the UnetLoaderGGUF node, which makes it impossible to use the SD3.5 model.
![1](https://github.com/user-attachments/assets/ee756452-32cf-454b-a4ce-4bcbedb00e2e)

**Comment by Arron17** [comment]
Just use the normal VAE loader and put in the SD 3.5 vae, the GGUF Checkpoints don't contain the Text Encoders or vae.

You can get the vae from here - https://huggingface.co/stabilityai/stable-diffusion-3.5-large/blob/main/vae/diffusion_pytorch_model.safetensors

Rename it to something that makes sense and put it in the models/vae folder.

**Comment by city96** [comment]
This is by design. The GGUF format is meant for 1 model per file, so it doesn't include the VAE. You can download the SD3 one from HF and use the VAELoader node or - alternatively - use the VAESave node and save the one from yor SD3.5 checkpoint then load that one separately.

![image](https://github.com/user-attachments/assets/1d2aa4fa-b226-49e3-8fb3-77e49927b6e8)

**Comment by Amazon90** [comment]
Thank you, I understand.
The gguf only contains the base model and does not include the VAE model.
I have downloaded the VAE model from https://huggingface.co/stabilityai/stable-diffusion-3.5-large/tree/main/vae
and successfully ran sd3.5.
