### ISSUE TITLE
Generates even slower than higher precision model

### ISSUE THREAD

**Issue by XJF2332** [city96/ComfyUI-GGUF#148]
This is fp8, safetensors
![image](https://github.com/user-attachments/assets/ea684adc-1e74-402f-a2b2-5d5dd7d14f8f)
And this is Q5, gguf, almost double the time
![image](https://github.com/user-attachments/assets/e914f431-a7d4-4e90-9eac-81a18ab0cc80)

same model, resolution, sampler, scheduler......everything is the same.

Did I do something wrong? Or did it just work fine?

**Comment by city96** [comment]
It should be slightly faster when you run it a second time with the model already loaded (the ksampler freezes for a bit at the start, that's where it's loading the model into memory).

Other than that, yeah, it's expected to be slower than FP8 due to the way dequantization is done. FP8 is a lot faster if you have an RTX 40XX card so that could be adding to it. Q5_1 as a quant is also fairly slow compared to Q4_0/Q8_0 iirc.

**Comment by XJF2332** [comment]
Yes, I am using a RTX40xx card, and these two images were captured at the second time. Should I use Q4? Because fp8 nearly ran out of all of my VRAM(not significant in SD3.5L, but I always get an Out of Memory in flux)

**Comment by city96** [comment]
Q4_0 with flux should still be fine I think. That's what I was using early on as well. The quants that have `K` in the name will be somewhat slower than the ones ending in `_0`, though the quality also tends to be better with K quants, something to keep in mind.
