### ISSUE TITLE
GGUF loader fails with quantized version of SD1.5 model

### ISSUE THREAD

**Issue by Metal-dude** [city96/ComfyUI-GGUF#160]
Hi, 

I made a GGUF version of a SD1.5 checkpoint I like (extracting unet then converting it to FP16 GGUF).

The result is very good, the GGUF loader loads the FP16 GGUF checkpoint, and I can't spot any difference in the images produced, compared to the original SD 1.5 safetensor checkpoint.

Then I used your method to make a quantized version of this FP16 GGUF : Q4_K_S.gguf

The GGUF loader loads this quantized  GGUF, but the result is very bad : images are just black ...

Do you know a solution ? I experiment so I'd like to understand.

**Comment by city96** [comment]
Could you check if setting this part to true makes it work? I might've accidentally set it to false during one of the rewrites for 1.5

https://github.com/city96/ComfyUI-GGUF/blob/8e898fad4caab59bf4144e0cf11978b893de7e54/tools/convert.py#L50

**Comment by city96** [comment]
Cool, looks like I missed that value when I originally rewrote that convert script. Changed it to true in the repo now so closing this.

As for LoRAs. Technically possible but doesn't seem worth it since they're fairly small + with default checkpoints they're baked into the main checkpoint (so it would only matter for storage, not vram usage) while with gguf checkpoints they'd have to be dequantized then applied on the fly (slowing them down further)
