### ISSUE TITLE
DualCLIPLoader (GGUF) needs hunyuan type

### ISSUE THREAD

**Issue by ABDe3N** [city96/ComfyUI-GGUF#183]
DualCLIPLoader (GGUF) needs hunyuan type to wrk with the new gguf text encoder

https://huggingface.co/IbnAbdeen/llava-llama-3-8b-text-encoder-tokenizer-Q8_0-GGUF/tree/main

**Comment by city96** [comment]
Done: https://github.com/city96/ComfyUI-GGUF/commit/8d1b56c5e2517219de12a01b742ed53cbaee463e

This was slightly more elaborate than just adding the mapping since I had to add the reverse of the permute logic llama.cpp uses [here](https://github.com/ggerganov/llama.cpp/blob/21ae3b9be83820565d1a720999b7f63ce95b4920/convert_hf_to_gguf.py#L1589-L1605) but it should work now. I'll put some imatrix quants up in a bit, which should in theory work better than the simple default ones you get from gguf-my-repo.

There's also some differences between whether you convert from the `-hf` or the `-transformers` repo for LLaVA 8B with the tokenizer missing ~64 extra tokens off the end for some reason.
