### ISSUE TITLE
Weights only load failed. Re-running

### ISSUE THREAD

**Issue by Cladislav** [city96/ComfyUI-GGUF#28]
Error occurred when executing DualCLIPLoader:

Weights only load failed. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
Please file an issue with the following so that we can make `weights_only=True` compatible with your use case: WeightsUnpickler error: Unsupported operand 168

**Comment by city96** [comment]
That message is from the DualCLIPLoader node, which is part of ComfyUI.
The issue is most likely the text encoder weights you downloaded and are trying to load - possibly a corrupt download or invalid file. You should most likely use the ones from [here](https://huggingface.co/comfyanonymous/flux_text_encoders/tree/main)

Open an issue report in the original ComfyUI repository if re-downloading them doesn't resolve it.

**Comment by Cladislav** [comment]
Reinstalled the encoder, the error remained.

**Comment by city96** [comment]
Then I recommend [opening an issue in the original repo](https://github.com/comfyanonymous/ComfyUI/issues)

It may also be worth following the instructions [here](https://comfyanonymous.github.io/ComfyUI_examples/flux/) to get it working without this custom node first and seeing if the issue can be replicated.

**Comment by Cladislav** [comment]
Figured it out, the problem was in the file clip-vit-large-patch14.bin downloaded [here](https://huggingface.co/openai/clip-vit-large-patch14/tree/main) 64 GB RAM 16GB VRAM, thank you

**Comment by ClothingAI** [comment]
Hello @Cladislav  so the clip-vit-large-patch14.bin is not compatible? why is that? I see it in the image in the description of this repo:
![image](https://github.com/user-attachments/assets/e731f37c-888b-4cbe-a647-dd8d9a2f541a)


What did you use in its stead?

Also, do  you have any idea what is the difference between all the 1.71 GB files on that page?
