### ISSUE TITLE
prompt for the image in README.md

### ISSUE THREAD

**Issue by kxm-dot** [city96/ComfyUI-GGUF#32]
Using this and its working great with no complaints, just wanted to ask what the prompt was for that main image? I'm having a hard time to get that style and i like what you did with the text :)

**Comment by city96** [comment]
It was actually super simple, though part of it was a lucky seed I think. Not sure you can 1:1 reproduce it since that was an early test Q4_0 quant lol but the rest of the settings are in the image.

```
an anime woman with white hair and elf ears with the text "The future is GGUF" above her head in big fancy graffiti letters.
The bottom of the image reads "4.5BPW is all you need!"
```

Some had a similar style font with that same prompt sans the bottom line:

![image](https://github.com/user-attachments/assets/dae67dcf-b90c-48e3-9838-83a00e954989)


Though most of the images with that same prompt came out more like this with the much lamer text:

![image](https://github.com/user-attachments/assets/38f7844f-8ec7-4b7f-987f-b505cd525a2c)
