### ISSUE TITLE
DualCLIPLoader  (GGUF) loaders vs DualCLIP Loader

### ISSUE THREAD

**Issue by rugabunda** [city96/ComfyUI-GGUF#55]
IF using a GGUF checkpoint, is there any difference between loading the clips in the GGUF vs the standard DudalCLIP loaders? Does it matter? I was using just the normal DualCLIP loader without any seeming issues, far as I could tell anyway...

**Comment by rugabunda** [comment]
I see, i have not seen any gguf versions of clips just yet, that will be cool!

**Comment by rugabunda** [comment]
Thanks!

**Comment by city96** [comment]
For CLIP you can use the normal .safetensors one since it's pretty small and the node can load both types of files.

**Comment by JorgeR81** [comment]
I was also able to load the T5 fp8, with the DualCLIPLoader (GGUF), using Flux.

**Comment by city96** [comment]
You mean Q8_0 right? The fp8 one works with just the default node.

**Comment by JorgeR81** [comment]
I have access to all encoders, via DualCLIPLoader (GGUF)

When I was trying some T5 GGUF ones, I also tried this `stableDiffusion3SD3_textEncoderT5E4m3fn`, which is a T5 fp8 I had since SD3, and it also worked. 
Then to be sure, I tried the T5 fp8, with the regular DualCLIPLoader node and the resulting image was the same. 

![dual](https://github.com/user-attachments/assets/cb319945-b911-4b70-9794-6aa98f7c7d42)

**Comment by JorgeR81** [comment]
I just tested with the `t5xxl_fp16` and it also works.
