### ISSUE TITLE
[Error log] clip missing: ['text_projection.weight']

### ISSUE THREAD

**Issue by Foul-Tarnished** [city96/ComfyUI-GGUF#69]
I sometimes get this error message in ComfyUI console, but not always:

```
Requested to load FluxClipModel_
Loading 1 new model
Requested to load Flux
Loading 1 new model
loaded completely 0.0 9400.242431640625 True
100%|██████████████████████████████████████████████████████████████████████████████████| 40/40 [01:04<00:00,  1.62s/it]
Requested to load AutoencodingEngine
Loading 1 new model
loaded completely 0.0 159.87335777282715 True
Prompt executed in 82.20 seconds
got prompt
clip missing: ['text_projection.weight']
Requested to load FluxClipModel_
Loading 1 new model
loaded completely 0.0 9319.23095703125 True
loaded completely 10599.324179870606 9400.242431640625 True
100%|██████████████████████████████████████████████████████████████████████████████████| 40/40 [01:49<00:00,  2.74s/it]
Requested to load AutoencodingEngine
Loading 1 new model
loaded completely 0.0 159.87335777282715 True
Prompt executed in 125.33 seconds
```
It happened at second generation, just after "got prompt"
(I selected in the console during last gen, so the stats are way slower)

both were with the same seed if that could be the issue
Result seem ok

I load T5 then clip if that impact it

**Comment by city96** [comment]
Blame SAI for that one, the `clip_l.safetensors` file they uploaded with SD3 and that everyone is using doesn't have that weight lol. For flux it shouldn't cause any issues since it's not used.

![image](https://github.com/user-attachments/assets/480b1e2e-0252-49bf-a967-4e42734ca0d3)

![image](https://github.com/user-attachments/assets/a812a3d6-4698-4dff-b631-fb64a7ddfb0b)
